[package]
name = "file-organizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "4.0.1"
fs_extra = "1.3.0"
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
